In [1]:
import pandas as pd 
import numpy as np 

In [2]:
DATA_PATH = "/home/prince/data_For_Project/archive(1)/Crop_recommendation.csv"
df_crop = pd.read_csv(DATA_PATH)

In [3]:
df_crop.head()

Nitrogen  phosphorus  potassium  temperature   humidity        ph  \
0        90          42         43    20.879744  82.002744  6.502985   
1        85          58         41    21.770462  80.319644  7.038096   
2        60          55         44    23.004459  82.320763  7.840207   
3        74          35         40    26.491096  80.158363  6.980401   
4        78          42         42    20.130175  81.604873  7.628473   

     rainfall label  Unnamed: 8  Unnamed: 9  
0  202.935536  rice         NaN         NaN  
1  226.655537  rice         NaN         NaN  
2  263.964248  rice         NaN         NaN  
3  242.864034  rice         NaN         NaN  
4  262.717340  rice         NaN         NaN

In [4]:
df_crop.shape

(2200, 10)

In [5]:
df_crop.isnull().sum()

Nitrogen          0
phosphorus        0
potassium         0
temperature       0
humidity          0
ph                0
rainfall          0
label             0
Unnamed: 8     2200
Unnamed: 9     2200
dtype: int64

In [6]:
 df_crop=df_crop.drop('Unnamed: 9', axis=1)
 df_crop=df_crop.drop('Unnamed: 8', axis=1)

In [7]:
df_crop.head()

Nitrogen  phosphorus  potassium  temperature   humidity        ph  \
0        90          42         43    20.879744  82.002744  6.502985   
1        85          58         41    21.770462  80.319644  7.038096   
2        60          55         44    23.004459  82.320763  7.840207   
3        74          35         40    26.491096  80.158363  6.980401   
4        78          42         42    20.130175  81.604873  7.628473   

     rainfall label  
0  202.935536  rice  
1  226.655537  rice  
2  263.964248  rice  
3  242.864034  rice  
4  262.717340  rice

In [8]:
df_crop=np.round(df_crop, 2)

In [9]:
new_df_crop=df_crop.copy()

In [10]:
new_df_crop['label'].value_counts()

label
rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: count, dtype: int64

In [11]:
crop_dict = {
    'rice':0,
     'maize':1,
     'jute':2,
     'cotton':3,
     'coconut':4,
     'papaya':5,
     'orange':6,
     'apple':7,
     'muskmelon':8,
     'watermelon':9,
     'grapes':10,
     'mango':11,
     'banana':12,
     'pomegranate':13,
     'lentil':14,
     'blackgram':15,
     'mungbean':16,
     'mothbeans':17,
     'pigeonpeas':18,
     'kidneybeans':19,
    'chickpea':20,
    'coffee':21
    }

In [12]:
new_df_crop['new_label'] = new_df_crop['label'].map(crop_dict)

In [13]:
new_df_crop.drop(['label'],axis=1,inplace=True)

In [14]:
new_df_crop.head()

Nitrogen  phosphorus  potassium  temperature  humidity    ph  rainfall  \
0        90          42         43        20.88     82.00  6.50    202.94   
1        85          58         41        21.77     80.32  7.04    226.66   
2        60          55         44        23.00     82.32  7.84    263.96   
3        74          35         40        26.49     80.16  6.98    242.86   
4        78          42         42        20.13     81.60  7.63    262.72   

   new_label  
0          0  
1          0  
2          0  
3          0  
4          0

In [15]:
X = new_df_crop.drop(['new_label'], axis=1) # features
y = new_df_crop['new_label'] # target

In [16]:
y.isnull().sum()

0

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    stratify=y,
                                                    random_state=40,
                                                    test_size=0.07
                                                    )


print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (2045, 7)
y_train shape: (2045,)
X_test shape: (155, 7)
y_test shape: (155,)


In [18]:
from sklearn.metrics import classification_report, confusion_matrix, \
            ConfusionMatrixDisplay, accuracy_score, precision_score, \
            recall_score, f1_score

In [19]:
from sklearn.linear_model import LogisticRegression
#Training Logistic Regression
logistic_clf = LogisticRegression(solver='saga',max_iter=10000,random_state=42)
logistic_clf.fit(X_train, y_train)

LogisticRegression(max_iter=10000, random_state=42, solver='saga')

In [20]:
y_hat = logistic_clf.predict(X_test)

In [21]:
cm=confusion_matrix(y_test,y_hat)
print(cm)

[[7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 6 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 5 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0]
 [0 0 0 0 0 0

In [22]:
accuracy_score(y_test,y_hat)

0.967741935483871

In [23]:
f1_score(y_test,y_hat,average='micro')

0.967741935483871

In [24]:
import xgboost as xgb
xgb_classifier = xgb.XGBClassifier(n_estimators=20, random_state=42)
xgb_classifier.fit(X_train, y_train)

/home/prince/.local/lib/python3.11/site-packages/xgboost/data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
/home/prince/.local/lib/python3.11/site-packages/xgboost/data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
/home/prince/.local/lib/python3.11/site-packages/xgboost/data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
/home/prince/.local/lib/python3.11/site-packages/xgboost/data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_ca

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=20, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [25]:
y_hat = xgb_classifier.predict(X_test)

/home/prince/.local/lib/python3.11/site-packages/xgboost/data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
/home/prince/.local/lib/python3.11/site-packages/xgboost/data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
/home/prince/.local/lib/python3.11/site-packages/xgboost/data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
/home/prince/.local/lib/python3.11/site-packages/xgboost/data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_ca

In [26]:
accuracy_score(y_test,y_hat)

0.9870967741935484

In [27]:
f1_score(y_test,y_hat,average='micro')

0.9870967741935484

In [28]:
import pickle
pickle.dump(xgb_classifier,open('crop_rec.pkl','wb'))